Andy/issue61
ubc-subbots/triton pull request #65
Opened 2021-02-14 02:16 UTC by AndyZhou1998

Thruster plugin with basic functionality of rotating and moving up. Added instructions on README under thruster simulation.

2021-02-20 19:02 UTC, JakeCronin1997 requested changes

2021-02-21 01:33 UTC, loganfillo commented on src/triton_gazebo/README.md
> +	python3 src/triton_gazebo/scripts/publisher_commands/run_thruster.py
Yeah I think it should either be a more comprehensive test node or removed

2021-02-28 22:03 UTC, JakeCronin1997 requested changes

2021-02-28 22:03 UTC, JakeCronin1997 commented on src/triton_gazebo/src/thruster_driver_plugin.cpp
>          thruster.push_back(_model->GetLink("triton_auv::thruster6::thruster"));
Populating the LinkPtr vector needs to be done in a loop using the thruster_count variable. right now were taking in an arbitrary array size but can only drive 6 anyways. 
replace all these push_backs with 
`for (int i = 0; i < this->thruster_count; i++)`
`{`
`    std::string thruster_name = (std::string)"triton_auv::thruster" + to_string(i) + (std::string)"::thruster";`
`    thruster.push_back(_model->GetLink(thruster_name));`
`}`

2021-02-28 23:50 UTC, JakeCronin1997 submitted a review, later dismissed

2021-03-01 00:09 UTC, JakeCronin1997 approved these changes

2021-03-01 00:10 UTC, merged